Completed exercise big-o-notation. - Jesus Araujo
j-alejandro-araujo/c0523-code-solutions pull request #71
Opened 2023-06-21 04:03 UTC by j-alejandro-araujo

![Screenshot 2023-06-20 at 9 02 34 PM](https://github.com/j-alejandro-araujo/c0523-code-solutions/assets/91649194/d5c2dea6-3921-4cca-872b-6f11e06406f2)

2023-06-26 05:59 UTC, shawnkost requested changes
Few changes requested here!

2023-06-26 05:59 UTC, shawnkost commented on big-o-notation/big-o.js
> +    const word = words[i]; // _ * _ = O(?) --> 2 * 1 = O(1)
Should be `O(n)`

2023-06-26 05:59 UTC, shawnkost commented on big-o-notation/big-o.js
> +      // _ * _ = O(?) --> 2 * 1 = O(1)
Should be `O(n)`

2023-06-26 05:59 UTC, shawnkost commented on big-o-notation/big-o.js
> +      unique[unique.length] = word; // _ * _ = O(?) --> 3 * 1 = O(1)
Should be `O(n)`

2023-06-26 05:59 UTC, shawnkost commented on big-o-notation/big-o.js
> +    const word = words[i]; // _ * _ = O(?) --> 2 * 1 = O(1)
Should be `O(n)`

2023-06-26 05:59 UTC, shawnkost commented on big-o-notation/big-o.js
> +    let isUnique = true; // _ * _ = O(?) --> 1 * 1 = O(1)
Should be `O(n)`

2023-06-26 05:59 UTC, shawnkost commented on big-o-notation/big-o.js
> +      const comparing = words[c]; // _ * _ = O(?) --> 2 * 1 = O(1)
Should be `O(n^2)`

2023-06-26 05:59 UTC, shawnkost commented on big-o-notation/big-o.js
> +        // _ * _ = O(?) --> 1 * 1 = O(1)
Should be `O(n^2)`

2023-06-26 05:59 UTC, shawnkost commented on big-o-notation/big-o.js
> +        isUnique = false; // _ * _ = O(?) --> 1 * 1 = O(1)
Should be `O(n^2)`

2023-06-26 05:59 UTC, shawnkost commented on big-o-notation/big-o.js
> +      // _ * _ = O(?) --> 1 * 1 = O(1)
Should be `O(n)`

2023-06-26 17:51 UTC, j-alejandro-araujo commented
Adjustments complete, thank you!

2023-06-29 16:43 UTC, TimelikeClosure requested changes

2023-06-29 16:43 UTC, TimelikeClosure commented on big-o-notation/big-o.js
> +      seen[word] = true; // _ * _ = O(?) --> 2 * 1 = O(1)
Should be `O(n)`.

2023-06-29 16:52 UTC, j-alejandro-araujo commented on big-o-notation/big-o.js
> +      seen[word] = true; // _ * _ = O(?) --> 2 * 1 = O(1)
Fixed!

2023-07-06 18:21 UTC, RobertGardner approved these changes

2023-07-06 19:14 UTC, merged